// <auto-generated/>
using System.Reflection;
using System.Resources;

[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyCompanyAttribute("Code Heroes")]
[assembly: AssemblyProductAttribute("CodeHeroes.CodeAnalysis.Style")]
[assembly: AssemblyCopyrightAttribute("© Copyright. Code Heroes.")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: NeutralResourcesLanguageAttribute("en-AU")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0")]
