//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Resources;

[assembly: AssemblyCompany("Code Heroes")]
[assembly: AssemblyProduct("CodeHeroes.CodeAnalysis.Style")]
[assembly: AssemblyVersion("0.0.1.0")]
[assembly: AssemblyFileVersion("0.0.1.0")]
[assembly: AssemblyInformationalVersion("0.0.1")]
[assembly: AssemblyCopyright("© Copyright. Code Heroes.")]
[assembly: AssemblyConfiguration("Release")]

// Custom Attributes
[assembly: NeutralResourcesLanguage("en-AU")]
